### ISSUE TITLE
environment config files

### ISSUE THREAD

**Issue by itised** [opulencephp/Project#2]
Is there a reason the environment config files are hidden (begin with a ".")?  Opulence doesn't use normal .env files, so compatibly with other tools for .env doesn't seem to be an issue. Is there a reason besides convention?

**Comment by davidbyoung** [comment]
Simply convention

**Comment by itised** [comment]
would you consider unhiding them?

following a .env file naming convention for a different file type was a bit confusing at first - it wasn't what I expected when I opened it. and it's also just easier to be able to see the files when browsing folders.

**Comment by davidbyoung** [comment]
I'll have to think about this one and get back to you.

**Comment by davidbyoung** [comment]
I've decided to keep them hidden because [they fit the use-case for dot files](http://askubuntu.com/questions/94780/what-are-dot-files).  I'm also going to keep the .env.***.php naming structure to clearly indicate that this hidden file is an environment config file.

Thanks for the feedback, though!  I had to think about this one for a while.
