### ISSUE TITLE
add default .htaccess

### ISSUE THREAD

**Issue by alchimik** [opulencephp/Project#5]
something like https://github.com/symfony/symfony-demo/blob/master/web/.htaccess

**Comment by davidbyoung** [comment]
I'd prefer not to have an .htaccess file in the skeleton project because it couples Opulence to Apache.  Also, .htaccess files are read on every single requests as opposed to server config files, which are only read once on server startup.  It does require a little bit of setup on your server, but hopefully my [documentation](https://www.opulencephp.com/docs#server-config) should help people get up and running.

**Comment by alchimik** [comment]
I missed that part of the documentation
